mysql_version: "5.6"       # centos版本 5.5 5.6 5.7  Ubuntu支持5.7和8.0
mysqlcluster_version: "7.6"   # 7.5 7.6 8.0
mysql_root_password: "123456" 


mysql_databases: []
#  - name: example 
#    encoding: utf8mb4
  
mysql_users: []
#  - name: example
#    host: localhost
#    password: password
#    priv: 'example.*:ALL'
