---
- name: pull onlyoffice/documentserver image
  docker_image:
    name: onlyoffice/documentserver

- name: Create certs directory
  file:
    path: /data/certs/onlyoffice_DocumentServer
    state: directory

- name: Copy certificate to certs directory
  copy:
    src: "{{item}}"
    dest: /data/certs/onlyoffice_DocumentServer
    mode: 0400
  with_items:
    - onlyoffice.crt
    - onlyoffice.csr
    - onlyoffice.key
    - dhparam.pem

- name: Run onlyoffice/documentserver
  docker_container:
    name: documentserver
    image: onlyoffice/documentserver
    restart_policy: always
    ports: 
      - "9002:80"
      - "9003:443"
    volumes: 
      - /data/certs/onlyoffice_DocumentServer:/var/www/onlyoffice/Data/certs
      - /data/logs/onlyoffice_DocumentServer:/var/log/onlyoffice
      - /data/wwwroot/onlyoffice_DocumentServer/data:/var/www/onlyoffice/Data
      - /data/wwwroot/onlyoffice_DocumentServer/lib:/var/lib/onlyoffice 
      - /data/onlyoffice_DocumentServer_postgresql:/var/lib/postgresql

